application: eladio-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico 

- url: /stylesheets
  static_dir: static/css

- url: .*
  script: main.app

- url: /signup
  script: main.app
  secure:always

- url: /login
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
